### ISSUE TITLE
Doc issues for tf provider

### ISSUE THREAD

**Issue by myoung34** [Scalr/documentation#192]
Then link for `edit on github` does not work for https://iacp.docs.scalr.com/en/latest/scalr-terraform-provider/index.html

all the snippets of 

```
provider scalr {
  hostname = "var.hostname"
  token    = "var.api_token"
}
```

are wrong. provider should be quoted, and vars should not: 

```
provider "scalr" {
  hostname = var.hostname
  token    = var.api_token
}
```

**Comment by myoung34** [comment]
also https://iacp.docs.scalr.com/en/latest/scalr-terraform-provider/data_sources/scalr_workspace.html

```
data scalr_workspace example {
  name         = "{workspace-name}"
  organization = "{environment-id}"
}
```

should be

```
data scalr_workspace "example" {
  name         = "{workspace-name}"
  organization = "{environment-id}"
}
```

**Comment by pgale61** [comment]
@myoung34 Thanks for these. You are correct regarding the quoted variables, but it is no longer necessary to quote provider, resource or data source names (and many other things).
